In [1]:
import pandas as pd
import numpy as np
from os.path import join
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, confusion_matrix 
from sklearn import linear_model
from sklearn.svm import SVC

In [11]:
path_raw = 'C:/Users/Benjamin/Documents/Mastere/Projet/data'


#file_members = 'members.csv'
#file_songs = 'songs.csv'
file_train = 'train.csv'
file_score='score_traina_genre_utilisateur.xlsx'
#file_test='test.csv'

In [12]:
#members = pd.read_csv(join(path_raw, file_members), error_bad_lines=False)
#songs = pd.read_csv(join(path_raw, file_songs), error_bad_lines=False)
train = pd.read_csv(join(path_raw, file_train), error_bad_lines=False)
score = pd.read_excel(join(path_raw, file_score), error_bad_lines=False)
#test = pd.read_csv(join(path_raw, file_test), error_bad_lines=False)

In [4]:
from sklearn.model_selection import train_test_split
traina, trainv = train_test_split(train, shuffle=True, test_size=0.3, stratify=train['target'])

In [ ]:
from sklearn import metrics
from sklearn.cluster import AgglomerativeClustering
from sklearn.cluster import KMeans

X=score
perf=[]
my_k=range(2,3)
for k in my_k:
    model=AgglomerativeClustering(k)
    y_pred=model.fit_predict(X)
    perf.append(metrics.calinski_harabaz_score(X.fillna(0),y_pred))

plt.plot(my_k,perf)

In [8]:
# Les utilisateurs qui ont plus de 10 chansons dans le trainPart
usr_more_song = trainPart.groupby(['msno'])['song_id'].agg('count')
usr_more_song = pd.DataFrame(usr_more_song).reset_index()
usr_more_song.columns = [['msno', 'song_number']]
usr_most = usr_more_song[usr_more_song.song_number >= 10]
print("Le nombre d'utilisateur avec plus de 10 chansons: ", len(usr_most))

Le nombre d'utilisateur avec plus de 10 chansons:  7678

In [9]:
# Je donne un numero à chaque utilisateur. Pour avoir une variable catégorielle dans mes données par la suite
usr_id = usr_most.reset_index(drop=True)
usr_id = usr_id.reset_index()
usr_id = usr_id[['index', 'msno']]
usr_id.columns = ['index_mem', 'msno']
usr_id.head()

   index_mem                                          msno
0          0  +/SKX44s4ryWQzYzuV7ZKMXqIKQMN1cPz3M8CJ8CFKU=
1          1  +0+XaewkS3za58vHwKCVGwRYRvjig4lTtKDV/tOkzbU=
2          2  +0B4aHABar5ltaWDG4M6KCzNxpD6wnsvZpvh+o9KgtE=
3          3  +0U8n45rrg6b5WCy3wpqOUYCwZyLqecr3lux9K6ahMk=
4          4  +0e12C+p9dzDbOvKjt8eElKH9yZPshAstxjm60XFgSM=

In [10]:
# Je donne également un numero à chaque chanson
song_more = trainPart.groupby(['song_id'])['msno'] .agg('count')
song_more = pd.DataFrame(song_more).reset_index()

song_id = song_more.reset_index(drop=True)
song_id = song_id.reset_index()
song_id = song_id[['index', 'song_id']]
song_id.columns = ['index_song', 'song_id']
song_id.head()

   index_song                                       song_id
0           0  ++7GdTgp8zbQLYOki7hVPEOHpu+KLZClsGrGiEuL2uI=
1           1  ++CfKs1t1wU1t0q0UxCdRqGoDpToqgMPmYytklaqo9o=
2           2  ++HlV9O/nnF8fmlWOgsrJSxO+rx75nHWuE6O3ykpVS8=
3           3  ++NP2gO99EW6w6sm4E1XP20nx8FhbBxsK9fOvbPHwd0=
4           4  ++QYBUGIUXrSsYfBPDW4PN5V6wnlJzLYCwP+FS9gMnY=

In [11]:
#On garde uniquement les chansons des 7678 utilisateurs
usr_list = list(usr_most.msno)
data = pd.DataFrame()
for usr in usr_list:
    data = data.append(trainPart[trainPart.msno == usr])

In [12]:
data.head()

,msno,song_id,source_system_tab,source_screen_name,source_type,target
65094,+/SKX44s4ryWQzYzuV7ZKMXqIKQMN1cPz3M8CJ8CFKU=,SiEK8IZqD9pbPgaG2GZWVO/WKE1e7Hnqhn/vlML3cqE=,my library,Local playlist more,local-library,1
65095,+/SKX44s4ryWQzYzuV7ZKMXqIKQMN1cPz3M8CJ8CFKU=,YN4T/yvvXtYrBVN8KTnieiQohHL3T9fnzUkbLWcgLro=,discover,Online playlist more,online-playlist,1
65096,+/SKX44s4ryWQzYzuV7ZKMXqIKQMN1cPz3M8CJ8CFKU=,9kvPtsVoRFyh96q8Sk+UiMAPPTaeVvwUAjAUXgpj9NM=,my library,Local playlist more,local-library,1
71256,+/SKX44s4ryWQzYzuV7ZKMXqIKQMN1cPz3M8CJ8CFKU=,KZ5hwP74wRO6kRapVIprwodtNdVD2EVD3hkZmmyXFPk=,discover,Online playlist more,online-playlist,1
71257,+/SKX44s4ryWQzYzuV7ZKMXqIKQMN1cPz3M8CJ8CFKU=,3VkD5ekIf5duJm1hmYTZlXjyl0zqV8wCzuAh3uocfCg=,discover,Online playlist more,online-playlist,1

In [13]:
#Encodage des variables catégorielles
encode_lab = LabelEncoder()
dataEncode = pd.get_dummies(data, columns=['source_system_tab', 'source_screen_name', 'source_type'])

In [14]:
# On modifie les colonnes de chansons et membres pour avoir que des valeurs numériques
dataEncode = dataEncode.merge(song_id, left_on='song_id', right_on='song_id')
dataEncode = dataEncode.merge(usr_id, left_on='msno', right_on='msno')

In [23]:
dataEncode.head()

,target,source_system_tab_discover,source_system_tab_explore,source_system_tab_listen with,source_system_tab_my library,source_system_tab_notification,source_system_tab_null,source_system_tab_radio,source_system_tab_search,source_system_tab_settings,...,source_type_local-library,source_type_local-playlist,source_type_online-playlist,source_type_radio,source_type_song,source_type_song-based-playlist,source_type_top-hits-for-artist,source_type_topic-article-playlist,index_song,index_mem
0,1,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,27631,0
1,1,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,32633,0
2,1,0,0,0,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,10651,0
3,1,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,20251,0
4,1,1,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,4962,0

In [18]:
dataEncode = dataEncode.iloc[:, 2:]

In [29]:
X = dataEncode.iloc[:, 1:]
Y = dataEncode['target']

In [30]:
#Split en train test
Xav, Xt, Yav, Yt = train_test_split(X, Y, shuffle=True, test_size=0.2, stratify=Y)
Xa, Xv, Ya, Yv = train_test_split(Xav, Yav, shuffle=True, test_size=0.3, stratify=Yav)

In [67]:
#%% Normalisation
sc = StandardScaler(with_mean=True, with_std=True)
sc = sc.fit(Xav)
Xav = sc.transform(Xav)
Xa = sc.transform(Xa)
Xv = sc.transform(Xv)
Xt = sc.transform(Xt)

In [69]:
Xt[['index_song','index_mem']] .head()

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [70]:
clf_reglog = linear_model.LogisticRegression(tol=1e-5, multi_class='multinomial', solver='lbfgs')
clf_reglog.C = 5
clf_reglog.fit(Xav, Yav)
print('Valeur de Copt = {}'.format(10 ))
print('RegLog: Err test correspondante = {}'.format(100*(1 - accuracy_score(Yt, clf_reglog.predict(Xt)))))
print('RegLog: Err apprentissage correspondante = {}'.format(100*(1 - accuracy_score(Yav, clf_reglog.predict(Xav)))))

Valeur de Copt = 10
RegLog: Err test correspondante = 23.63819950045172
RegLog: Err apprentissage correspondante = 23.64437555358725

In [76]:
Xav

array([[ 2.07336742, -0.12390192, -0.14038421, ..., -0.02847998,
         1.32789926, -1.5230517 ],
       [-0.48230718, -0.12390192, -0.14038421, ..., -0.02847998,
         0.89535619,  1.58151586],
       [-0.48230718, -0.12390192, -0.14038421, ..., -0.02847998,
         1.01760057,  0.80446779],
       ...,
       [-0.48230718, -0.12390192, -0.14038421, ..., -0.02847998,
        -1.27854924, -0.93584803],
       [-0.48230718, -0.12390192, -0.14038421, ..., -0.02847998,
         0.68782504,  0.42795062],
       [-0.48230718, -0.12390192, -0.14038421, ..., -0.02847998,
        -1.44972766,  0.54801927]])

In [47]:
Yav[Xav[['index_song','index_mem']].loc[Xav['index_mem']==0].index]

4     1
6     1
2     1
13    1
10    1
1     1
14    0
9     1
5     1
21    1
15    1
8     1
0     1
19    0
17    1
20    1
11    1
12    1
Name: target, dtype: int64

In [43]:
Xav[['index_song','index_mem']].loc[Xav['index_mem']==0]

    index_song  index_mem
4         4962          0
6        13294          0
2        10651          0
13       40655          0
10       56225          0
1        32633          0
14       43752          0
9         9093          0
5          332          0
21       52303          0
15       42729          0
8        50793          0
0        27631          0
19       54559          0
17       14688          0
20       25417          0
11       56610          0
12         636          0

In [46]:
Xav[['index_song','index_mem']].loc[Xav['index_song']==4962]

       index_song  index_mem
4            4962          0
19497        4962       2097
55714        4962       7557
43555        4962       2491
47600        4962       4402
45794        4962       3448
44082        4962       2647
53109        4962       6510
45154        4962       2994
31680        4962       5703
28489        4962       4835
40455        4962       1315
35333        4962       7329
52888        4962       6286
43044        4962       2334
15153        4962        468
4310         4962       3011
51176        4962       5800
42269        4962       2085
30811        4962       5423
46400        4962       3873
42475        4962       2161
29317        4962       5045
54127        4962       7020
43638        4962       2501
53944        4962       6930
20763        4962       2560
38294        4962        644
15241        4962        511
53696        4962       6856
...           ...        ...
45614        4962       3251
40308        4962       1296
28994        4962       5012
40152        4962       1244
33739        4962       6651
55696        4962       7539
40064        4962       1174
15216        4962        507
17238        4962       1265
42878        4962       2288
53425        4962       6622
42424        4962       2150
46343        4962       3777
43491        4962       2463
37789        4962        478
34777        4962       7218
44472        4962       2881
33523        4962       6541
38590        4962        740
296          4962         17
39463        4962       1050
18332        4962       1770
47837        4962       4492
50819        4962       5591
54178        4962       7024
38155        4962        587
39882        4962       1127
18423        4962       1795
50411        4962       5342
41096        4962       1741

[449 rows x 2 columns]

In [48]:
Yav[Xav[['index_song','index_mem']].loc[Xav['index_song']==4962].index]

4        1
19497    1
55714    1
43555    1
47600    1
45794    1
44082    1
53109    1
45154    1
31680    1
28489    1
40455    1
35333    1
52888    1
43044    1
15153    1
4310     1
51176    0
42269    1
30811    1
46400    0
42475    1
29317    0
54127    0
43638    1
53944    1
20763    1
38294    1
15241    1
53696    1
        ..
45614    1
40308    1
28994    1
40152    1
33739    1
55696    1
40064    1
15216    1
17238    1
42878    1
53425    1
42424    1
46343    1
43491    1
37789    1
34777    1
44472    1
33523    0
38590    1
296      1
39463    0
18332    1
47837    1
50819    1
54178    1
38155    0
39882    1
18423    1
50411    1
41096    0
Name: target, Length: 449, dtype: int64

In [4]:
music=songs[['song_id','genre_ids']]
music['song_id']=music.index
songs

C:\Users\Benjamin\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,song_id,song_length,genre_ids,artist_name,composer,lyricist,language
0,CXoTN1eb7AI+DntdU1vbcwGRV4SCIDxZu+YD8JP8r4E=,247640,465,張信哲 (Jeff Chang),董貞,何啟弘,3.0
1,o0kFgae9QtnYgRkVPqLJwa05zIhRlUjfF7O1tDw0ZDU=,197328,444,BLACKPINK,TEDDY| FUTURE BOUNCE| Bekuh BOOM,TEDDY,31.0
2,DwVvVurfpuz+XPuFvucclVQEyPqcpUkHR0ne1RQzPs0=,231781,465,SUPER JUNIOR,NaN,NaN,31.0
3,dKMBWoZyScdxSkihKG+Vf47nc18N9q4m58+b4e7dSSE=,273554,465,S.H.E,湯小康,徐世珍,3.0
4,W3bqWd3T+VeHFzHAUfARgW9AvVRaF4N5Yzm4Mr6Eo/o=,140329,726,貴族精選,Traditional,Traditional,52.0
5,kKJ2JNU5h8rphyW21ovC+RZU+yEHPM+3w85J37p7vEQ=,235520,864|857|850|843,貴族精選,Joe Hisaishi,Hayao Miyazaki,17.0
6,N9vbanw7BSMoUgdfJlgX1aZPE1XZg8OS1wf88AQEcMc=,226220,458,伍佰 & China Blue,Jonathan Lee,NaN,3.0
7,GsCpr618xfveHYJdo+E5SybrpR906tsjLMeKyrCNw8s=,276793,465,光良 (Michael Wong),光良,彭資閔,3.0
8,oTi7oINPX+rxoGp+3O6llSltQTl80jDqHoULfRoLcG4=,228623,465,林俊傑 (JJ Lin),JJ Lin,Wu Qing Feng,3.0
9,btcG03OHY3GNKWccPP0auvtSbhxog/kllIIOx5grE/k=,232629,352|1995,Kodaline,Stephen Garrigan| Mark Prendergast| Vincent Ma...,Stephen Garrigan| Mark Prendergast| Vincent Ma...,52.0
10,HulM/OaHgD5kUyjNQjDUf8VZdsy7h4EJUIff79Cifwo=,272544,2157,D.L 羅時豐 (Daniel Lo),陳偉強,陳偉強,10.0
11,wypPzqFNdUJAqyBVxmFGaK4z7krUNWr5YqA0q0wi9eE=,254880,465,白安 (Ann),白安,白安,3.0
12,fAZLdfQaLG76a6Ei4alt1eSjBM9rshQkiQEC6+n+y08=,180871,726,Littlesong,Michael William Balfe,NaN,-1.0
13,tqBlH4r/q1Tf6C5+C6ucjGlLjMbfu5yjqB6ifRzy5dc=,257602,458,蔡旻佑 (Evan Yo),蔡旻佑,陳信延,3.0
14,an6EdIr+Z+KbqIVQiXn5PKkcXncefQ7hhWONseRuub4=,282697,359,Coldplay,Chris Martin| Guy Berryman| Jonny Buckland| Mi...,NaN,52.0
15,J2MFmy8iF94mExWfRWE3KxsMZB+ZIedV5liqZoSrERQ=,221518,359,Maggie Rogers,Maggie Rogers| Nicholas Das,NaN,52.0
16,MrRilXQwoUAcoAf0N3RT82qX2/us/wEhYDXE+ZTIW5o=,199157,458,小男孩樂團 (Men Envy Children),"Skot Suyama陶山/""蔡詩蕓 Dominique Tsai""",程懷昌 Vince Cheng,3.0
17,OcG4Ya7iXmVMCMy24C5wxDMtr9w6WQZiFaN0uq6zdTk=,169430,465,BIGBANG,TAEYANG| TEDDY,G-DRAGON| T.O.P| TEDDY,3.0
18,JcHIgDP5ivyqYIn7RxfXM13eWwOzcoxkWosSauz6RbU=,374027,726,White Noise,NaN,NaN,-1.0
19,3Po6v5nAk+ACnmTgGF4maCQNwWCuCT9BSR13M5c8KG8=,246015,465,步步驚心主題曲原聲EP,嚴藝丹,嚴藝丹,3.0
20,IV8kTOBKcUoO4fINEi+VTYzr7TdyM/kin+gapgzygco=,228993,465,Katy Perry,Katy Perry| Max Martin| Lukasz Gottwald| Henry...,NaN,52.0
21,XtT+taE0f0Ua5O96nZ48vW+r8YwRgO6WdWOoJmmDUNU=,226951,465,劉若英 (Rene Liu),張起政,廖瑩如,3.0
22,XVdugYtHPN1vCK/8rsZZj/5MX8wv421d4unsaOpPq7I=,292571,465,傅又宣 (Maggie Fu),陶山,方文山,3.0
23,FZ5/wgtMuMV0Y8gzzgQj6bH3Qpr62zRV/LwbhNBrdqk=,220056,465,BIGBANG TAEYANG,NaN,NaN,31.0
24,bTM25FJNlCHnltU0hhQDFAzdnOYsobmfCwwAnN1K2a8=,430080,1609,Danny Marquez & Ferry B,NaN,NaN,52.0
25,SONqxocCptA85J/tJ1hGlTVbQxs+x1gokyes79xZFO0=,266788,1609,Kyary Pamyu Pamyu (きゃりーぱみゅぱみゅ),Yasutaka Nakata,Yasutaka Nakata,17.0
26,Co8PcF2DeW+i14x4xSwe7YFkJKAm1B8SZNXdVTpsljc=,240326,465,品冠 (Victor Wong),品冠,戴佩妮,3.0
27,+M/yM08pYwOznHRvf9Aj95A9M85wn4/jsTX0ye1KR2c=,281054,139,The Weeknd,Abel Tesfaye| Timothy Mckenzie| Carlo Montagnese,NaN,52.0
28,+dOlHQGlsiHPbG1cMYsoFVsAi05YgsGfeEzsdS16yec=,368441,1609,Marvin Gaye & Kygo,Marvin Gaye| Odell Brown| David Ritz,Marvin Gaye| Odell Brown| David Ritz,-1.0
29,gG3/58uZyyOwaPT+eGWL81mwCzcDPW2EmwYcjWmvJSs=,226742,465,五月天 (Mayday),阿信,阿信,3.0
...,...,...,...,...,...,...,...
2296290,oVtifsDFiwh2WQeUdyUBoz7vCYtxeBhPEnw5brXt70Y=,69381,1259,Charley Brownn,Mawwell J. Mckinney,NaN,52.0
2296291,GCRKexNnu1nvpXYAg6AqkRs9Yys1/8HVZ+jA4rzWNCk=,417100,880,Jason Nelson,NaN,NaN,52.0
2296292,nnIHjbQeA+mXbD0EPdu+CkrodY89T6KuWhGzx6sP9tI=,216502,465,Amanda Perez,Amanda Perez,NaN,52.0
2296293,+YkZMWKLe7u7Wh0Ex5UhcaF0bGgbbD7MGDPwmyxUcLU=,285231,958,鈴木理恵子/若林顕,Franz Schubert,NaN,-1.0
2296294,LIBVFt9mqBUtZu911th7hIuQ6ecZJEZYr3k8drsqEGI=,309404,465,Mecano,Ignacio Cano,Ignacio Cano,52.0
2296295,JeUrksZKJRDKpFm8z6fCQ/HwSgmsyYU4hbBnYVV9lE8=,329630,139|125|109,Peabo Bryson,NaN,NaN,-1.0
2296296,fJJrEGbSljSyQHL8rUZVsNfWjhiOSLzlcrDcpwTKcEE=,276584,465,Avaleya and The GlitterHawks,NaN,NaN,52.0
2296297,CZ9wDBohPNyoC/j3OULasa4KJA4GranPYxFXfPoH9FQ=,228019,1259,Father,NaN,NaN,52.0
2296298,i75zV121vPNEnvQpAQdaeO85VorQ6dESl2583HsmgCE=,259877,359,FAIRCHILD,Adam Lyons| Nathan Lyons| Timothy Voeten| Patr...,NaN,52.0
2296299,ACYeQ/Mq+hfwlkdOLBXiVPamqZnxTsOu3jLcCcEGDgU=,157338,2022,Various Artists,Dave Appell| Kal Mann,NaN,52.0
2296300,UW46DgkpCRkftdFzQbUbYOE7LU+U/dtTY27a8QxG/xQ=,97212,958,Seiji Ozawa (小澤征爾),Igor Stravinsky,NaN,-1.0
2296301,HpAyT/rz9ta5hku/j/COjmjVXY0XNFjsMnT454rbfqU=,255922,388,Yin Yoga Academy,Sacchetto G.,NaN,-1.0
2296302,9w0/At83TBWVHIMHJsLWc4XkSt6rtQWrhgPS5VkDGBw=,167481,1011,Kenny Chesney,Rodney Clawson| Vicky McGehee| David Lee Murphy,Rodney Clawson| Vicky McGehee| David Lee Murphy,52.0
2296303,+ZPZAAPCcPSL0EnVA8Wv/QxI9xdbL/3GPCXLdA//I6k=,334053,1616,Renato pezzella| Renato Pezzella,NaN,NaN,52.0
2296304,drhKIG4cRzpkiJaW0gem3MpKBNAHziSggBiiMjyZzWE=,263836,958,Felix Mendelssohn,NaN,NaN,-1.0
2296305,+HEDP6j6Pp6/uWt4yUtDnwVUdN/7yjSAxP/c2K8ff1A=,281077,465,欒生,欒生,欒生,3.0
2296306,b2TN2bI6sO05QpFYHY2AtwYr1wIxQ4FilfOqdzyHXWg=,153716,2122,Michael Silverman Jazz Piano Trio,NaN,NaN,-1.0
2296307,zH1JEkk62Zn1a4cn89jNoNnKgPZ8jzQrlCu4+u/UC90=,235728,359,Philip Selway,Philip Selway,Philip Selway,52.0
2296308,Owx3cSol+W6baFmASRMBBv6L5umzHane8s0oJM/kU5k=,229041,465,Noosa Hedz,NaN,NaN,52.0
2296309,3nhlABC5FK3T0vk5oHxM8+5ujO1FawqSw1yNpFRvaCA=,388022,1616|2058,Bobby Gasparakis| Edo Mela| Bodega| Randy Garc...,NaN,NaN,52.0
2296310,UcUZh2+hem1XsHnDdkYSAiWmZmD2eVtA5e0SK/FUCGs=,60081,958,Orgel Carrol 오르골캐롤,NaN,NaN,-1.0
2296311,dI8nj1sIoA4JzQlPUhwsRLS9cNj1yTZGUOFVRx1LJb4=,185945,465,Karen Jonas,NaN,NaN,52.0
2296312,UmVIdVUcfq15Egwrv2m3zbqVxkuzCTL1rWJ2lBd5GGs=,233964,1572|275,The Jackals,NaN,NaN,52.0
2296313,/CAX/IYPCRN++OIqEX8arRHs1RTeQKYLouEeyFakD6Y=,158452,465,Various Artists,NaN,NaN,52.0
2296314,m2gnQUTljZUJntDrhBvv19UUhe87T5zPIJ355ge52Z4=,75418,2122,Art Blakey & The Jazz Messengers,Art Blakey| Benny Golson,NaN,52.0
2296315,lg6rn7eV/ZNg0+P+x77kHUL7GDMfoL4eMtXxncseLNA=,20192,958,Catherine Collard,Robert Schumann (1810-1856),NaN,-1.0
2296316,nXi1lrSJe+gLoTTNky7If0mNPrIyCQCLwagwR6XopGU=,273391,465,紀文惠 (Justine Chi),NaN,NaN,3.0
2296317,9KxSvIjbJyJzfEVWnkMbgR6dyn6d54ot0N5FKyKqii8=,445172,1609,Various Artists,NaN,NaN,52.0
2296318,UO8Y2MR2sjOn2q/Tp8/lzZTGKmLEvwZ20oWanG4XnYc=,172669,465,Peter Paul & Mary,NaN,NaN,52.0
2296319,V/9qPSUOGT0FeIGBhDIZRRz5Y5yyjdXC2Z/+bJExo5s=,270466,829,Kim Robertson,NaN,NaN,52.0

In [5]:
a=pd.DataFrame([str(element).split('|') for element in songs['genre_ids']])
a=pd.get_dummies(a)

In [6]:
song_tr=pd.concat([songs['song_id'], a], axis=1)
song_tr['id']=song_tr.index

In [7]:
members['id']=members.index

In [8]:
Xtr=train.iloc[:,0:2].merge(song_tr, on='song_id').merge(members[['msno','id']], on='msno')

In [11]:
Xtr = Xtr.drop(['msno','song_id'],1)

In [ ]:
Xtr = pd.read_csv('C:/Users/Benjamin/Documents/Mastere/Projet/songs_user.csv')

In [ ]:
Xtr.head

In [68]:
ytr=train.iloc[:,-1]

In [72]:
Xte=test.iloc[:,1:3].merge(song_tr, on='song_id').merge(members[['msno','id']], on='msno')
Xte = Xte.drop(['msno','song_id'],1)

In [73]:
Xte

            0     1     2     3     4     5     6     7     id_x   id_y
0         458  None  None  None  None  None  None  None   361250  29464
1         465  None  None  None  None  None  None  None     2684  29464
2         465  None  None  None  None  None  None  None   361223  29464
3         465  None  None  None  None  None  None  None   333110  29464
4         465  None  None  None  None  None  None  None   166393  29464
5         458  None  None  None  None  None  None  None  1685961  29464
6         465  None  None  None  None  None  None  None   564669  29464
7         465  None  None  None  None  None  None  None    33455  29464
8         465  None  None  None  None  None  None  None    68238  29464
9         458  None  None  None  None  None  None  None   108394  29464
10        465  None  None  None  None  None  None  None    46915  29464
11        465  None  None  None  None  None  None  None    22792  29464
12        465  None  None  None  None  None  None  None  1190917  29464
13        465  None  None  None  None  None  None  None    28130  29464
14        458  None  None  None  None  None  None  None   412179  29464
15        458  None  None  None  None  None  None  None   187655  29464
16        465  2122  None  None  None  None  None  None   106989  29464
17        458  None  None  None  None  None  None  None   361250  23971
18        458  None  None  None  None  None  None  None   648916  23971
19        458  None  None  None  None  None  None  None   790435  23971
20        458  None  None  None  None  None  None  None   387963  23971
21        458  None  None  None  None  None  None  None    72255  23971
22        465  None  None  None  None  None  None  None  1660772  23971
23        465  None  None  None  None  None  None  None   136485  23971
24        465  None  None  None  None  None  None  None    58905  23971
25        465  None  None  None  None  None  None  None   473585  23971
26        458  None  None  None  None  None  None  None   211414  23971
27        465  None  None  None  None  None  None  None   654296  23971
28        451  None  None  None  None  None  None  None   163283  23971
29        465  None  None  None  None  None  None  None   128480  23971
...       ...   ...   ...   ...   ...   ...   ...   ...      ...    ...
2556735  1609  None  None  None  None  None  None  None   158465  19200
2556736   465  None  None  None  None  None  None  None  1939269  27963
2556737   465  None  None  None  None  None  None  None  2251398  27963
2556738   465  None  None  None  None  None  None  None   219788  27963
2556739   465  None  None  None  None  None  None  None    76078  27963
2556740   940  1152  None  None  None  None  None  None   129949   1126
2556741   458  None  None  None  None  None  None  None   655141   7412
2556742   458  None  None  None  None  None  None  None   655141  10137
2556743   458  None  None  None  None  None  None  None   655141  22041
2556744   nan  None  None  None  None  None  None  None   104028   8728
2556745  2022  None  None  None  None  None  None  None   474626   8129
2556746  1609  None  None  None  None  None  None  None   211077   7727
2556747   458  None  None  None  None  None  None  None    64707  20646
2556748   921  None  None  None  None  None  None  None    24903  33984
2556749   545  None  None  None  None  None  None  None   263925  33524
2556750   465  None  None  None  None  None  None  None  1055024  26626
2556751   786  None  None  None  None  None  None  None   337986  26626
2556752   465  None  None  None  None  None  None  None   305110  26626
2556753   444  None  None  None  None  None  None  None   511064   1242
2556754   444  None  None  None  None  None  None  None   135652   1242
2556755   444  None  None  None  None  None  None  None   855199   1242
2556756   444  None  None  None  None  None  None  None    55499   1242
2556757   444  None  None  None  None  None  None  None   273405   1242
2556758   444  None  None  None  None  None  None  None  1500943   1242
2556759   444  None  None  None  None  None  None  None    56645   1242
2556760   444  None  None  None  None  None  None  None  1214365   1242
2556761   444  None  None  None  None  None  None  None   258770   1242
2556762   444  None  None  None  None  None  None  None   413917   1242
2556763   444  None  None  None  None  None  None  None   298882   1242
2556764   444  None  None  None  None  None  None  None   982058   1242

[2556765 rows x 10 columns]

In [102]:
Xtr.drop(Xtr.index[np.where(Xtr[0]=='nan')])

            0     1     2     3     4     5     6     7     id_x   id_y
0         359  None  None  None  None  None  None  None  1391177  21893
1        1011  None  None  None  None  None  None  None   518476  21893
2        1259  None  None  None  None  None  None  None    10719  21893
3        1011  None  None  None  None  None  None  None   163440  21893
4         465  None  None  None  None  None  None  None   387975  21893
5         465  None  None  None  None  None  None  None    46833  21893
6         465   458  None  None  None  None  None  None    52185  21893
7         458  None  None  None  None  None  None  None    97709  21893
8         465  None  None  None  None  None  None  None    93696  21893
9        1259  None  None  None  None  None  None  None    32125  21893
10        465  None  None  None  None  None  None  None   604773  21893
11        465  None  None  None  None  None  None  None  1035362  21893
12        458  None  None  None  None  None  None  None  1305441  21893
13        458  None  None  None  None  None  None  None    29450  21893
14        458  None  None  None  None  None  None  None    21409  21893
15        458  None  None  None  None  None  None  None   379923  21893
16        458  None  None  None  None  None  None  None     6692  21893
17        465  None  None  None  None  None  None  None    60219  21893
18        465  None  None  None  None  None  None  None  1938250  21893
19        465  None  None  None  None  None  None  None   244856  21893
20        465  None  None  None  None  None  None  None   172853  21893
21        921  None  None  None  None  None  None  None   215440  21893
22        458  None  None  None  None  None  None  None     4014  21893
23        465  None  None  None  None  None  None  None   977536  21893
24        465  1259  None  None  None  None  None  None   526248  21893
25        465  None  None  None  None  None  None  None    77699  21893
26        465  None  None  None  None  None  None  None    14727  21893
27        465  None  None  None  None  None  None  None    97677  21893
28       1609  None  None  None  None  None  None  None   141836  21893
29        458  None  None  None  None  None  None  None  1660520  21893
...       ...   ...   ...   ...   ...   ...   ...   ...      ...    ...
7377273   458  None  None  None  None  None  None  None   141829  32040
7377274   458  None  None  None  None  None  None  None   141829  21305
7377275   458  None  None  None  None  None  None  None   141829  18145
7377276   458  None  None  None  None  None  None  None   141829  22494
7377277   458  None  None  None  None  None  None  None   141829  18362
7377278   458  None  None  None  None  None  None  None   141829  22171
7377279   458  None  None  None  None  None  None  None   141829  18550
7377280   458  None  None  None  None  None  None  None   141829  10322
7377281   458  None  None  None  None  None  None  None   141829  23502
7377282   458  None  None  None  None  None  None  None   141829  26708
7377283   458  None  None  None  None  None  None  None   141829   6299
7377284   458  None  None  None  None  None  None  None   141829  11433
7377285   458  None  None  None  None  None  None  None   141829    577
7377286   458  None  None  None  None  None  None  None   141829  21418
7377287   458  None  None  None  None  None  None  None   141829  27833
7377288   458  None  None  None  None  None  None  None   141829  18072
7377289   458  None  None  None  None  None  None  None   141829  14731
7377290   458  None  None  None  None  None  None  None   141829  19235
7377291   458  None  None  None  None  None  None  None   141829   9012
7377292   465  None  None  None  None  None  None  None   278829   9012
7377293   465  None  None  None  None  None  None  None  1090919   9012
7377294   458  None  None  None  None  None  None  None   141829  21721
7377295  1609  None  None  None  None  None  None  None   210067  18896
7377296   465  None  None  None  None  None  None  None   553551  34318
7377297   458  None  None  None  None  None  None  None   462011  24500
7377298  1011  None  None  None  None  None  None  None  1557692  21801
7377300   726  None  None  None  None  None  None  None   675809  31173
7377301   465  None  None  None  None  None  None  None   794942  31173
7377302   465  None  None  None  None  None  None  None   301639  31173
7377303   465  None  None  None  None  None  None  None  1063936  12676

[7258963 rows x 10 columns]

In [108]:
from sklearn import linear_model
clr=linear_model.LinearRegression()
clr.fit(Xtr,ytr)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [ ]:
clrf.predict()